### ISSUE TITLE
Super Slow and loses Connection every 30 minutes

### ISSUE THREAD

**Issue by TheMRX13** [itchannel/tdarr_ha#43]
See title. The Integration is super slow. Updateing the entitys needs arround 40 seconds and i have set it to 30 seconds. Loses connection every 30 minutes. Every entitys goes unavailble for arround 1 - 2 minutes

**Comment by itchannel** [comment]
Can you please enable debug logging and provide a copy of the tdarr logs from home assistant. As well as plugin version and HA version. I am unable to replicate your issue as its been working fine for me for months.

**Comment by TheMRX13** [comment]
i try to get that. Next what i found. i cant change the Update delay. i can set it high or lower. it always saves 30 Seconds. 
Tdarr is connected over Local network. Link speed is 1 Gbit.

the Only Log what i can Provide now is 

```
2025-04-29 10:02:40.448 DEBUG (MainThread) [custom_components.tdarr] Finished fetching tdarr data in 29.050 seconds (success: True)
2025-04-29 10:02:40.448 DEBUG (MainThread) [custom_components.tdarr.sensor] {'totalFiles': 36600, 'totalTranscodeCount': 30064, 'sizeDiff': 529.7688494734466, 'totalHealthCheckCount': 83650, 'status': {'transcode': [{'name': 'Not required', 'value': 6381}, {'name': 'Queued', 'value': 29}, {'name': 'Transcode success', 'value': 30190}], 'healthcheck': [{'name': 'Queued', 'value': 38}, {'name': 'Success', 'value': 36562}]}, 'video': {'codecs': [{'name': 'h264', 'value': 31}, {'name': 'hevc', 'value': 36507}, {'name': 'vp9', 'value': 24}], 'containers': [{'name': 'mkv', 'value': 36533}, {'name': 'ts', 'value': 29}], 'resolutions': [{'name': '1080p', 'value': 3217}, {'name': '1440p', 'value': 2}, {'name': '480p', 'value': 10384}, {'name': '4KUHD', 'value': 1}, {'name': '576p', 'value': 1683}, {'name': '720p', 'value': 21275}]}, 'audio': {'codecs': [{'name': 'aac', 'value': 38}], 'containers': [{'name': 'ts', 'value': 38}]}, 'name': 'All'}
2025-04-29 10:02:40.449 DEBUG (MainThread) [custom_components.tdarr.sensor] {'totalFiles': 3609, 'totalTranscodeCount': 2600, 'sizeDiff': 354.41779433283955, 'totalHealthCheckCount': 8372, 'status': {'transcode': [{'name': 'Not required', 'value': 1068}, {'name': 'Queued', 'value': 29}, {'name': 'Transcode success', 'value': 2512}], 'healthcheck': [{'name': 'Success', 'value': 3609}]}, 'video': {'codecs': [{'name': 'h264', 'value': 29}, {'name': 'hevc', 'value': 3580}], 'containers': [{'name': 'mkv', 'value': 3580}, {'name': 'ts', 'value': 29}], 'resolutions': [{'name': '1080p', 'value': 1580}, {'name': '480p', 'value': 52}, {'name': '4KUHD', 'value': 1}, {'name': '576p', 'value': 1}, {'name': '720p', 'value': 1975}]}, 'audio': {'codecs': [], 'containers': []}, 'name': 'Platte 1 - D'}
2025-04-29 10:02:40.449 DEBUG (MainThread) [custom_components.tdarr.sensor] {'totalFiles': 32991, 'totalTranscodeCount': 25969, 'sizeDiff': 2.28257907461375, 'totalHealthCheckCount': 74296, 'status': {'transcode': [{'name': 'Not required', 'value': 5313}, {'name': 'Transcode success', 'value': 27678}], 'healthcheck': [{'name': 'Queued', 'value': 38}, {'name': 'Success', 'value': 32953}]}, 'video': {'codecs': [{'name': 'h264', 'value': 2}, {'name': 'hevc', 'value': 32927}, {'name': 'vp9', 'value': 24}], 'containers': [{'name': 'mkv', 'value': 32953}], 'resolutions': [{'name': '1080p', 'value': 1637}, {'name': '1440p', 'value': 2}, {'name': '480p', 'value': 10332}, {'name': '576p', 'value': 1682}, {'name': '720p', 'value': 19300}]}, 'audio': {'codecs': [{'name': 'aac', 'value': 38}], 'containers': [{'name': 'ts', 'value': 38}]}, 'name': 'Platte 2 - G'}
```

As soon Tdarr loses connection ill post an update

**Comment by TheMRX13** [comment]
Integration Version: 1.18-Release
HA Operating System: 15.2
HA Core: 2025.4.4
HA Supervisor: 2025.04.1

Tdarr loses connection with this on Log. Here is a Picture too.

```
2025-04-29 10:11:08.975 DEBUG (MainThread) [custom_components.tdarr] Node Change Detected config reload required
2025-04-29 10:11:08.975 DEBUG (MainThread) [custom_components.tdarr] SHOWING ENTRY
2025-04-29 10:11:08.976 DEBUG (MainThread) [custom_components.tdarr] Finished fetching tdarr data in 24.720 seconds (success: True)
2025-04-29 10:11:08.976 DEBUG (MainThread) [custom_components.tdarr.sensor] {'totalFiles': 36600, 'totalTranscodeCount': 30067, 'sizeDiff': 530.0468513416126, 'totalHealthCheckCount': 83652, 'status': {'transcode': [{'name': 'Not required', 'value': 6381}, {'name': 'Queued', 'value': 26}, {'name': 'Transcode success', 'value': 30193}], 'healthcheck': [{'name': 'Queued', 'value': 39}, {'name': 'Success', 'value': 36561}]}, 'video': {'codecs': [{'name': 'h264', 'value': 28}, {'name': 'hevc', 'value': 36510}, {'name': 'vp9', 'value': 24}], 'containers': [{'name': 'mkv', 'value': 36536}, {'name': 'ts', 'value': 26}], 'resolutions': [{'name': '1080p', 'value': 3217}, {'name': '1440p', 'value': 2}, {'name': '480p', 'value': 10384}, {'name': '4KUHD', 'value': 1}, {'name': '576p', 'value': 1683}, {'name': '720p', 'value': 21275}]}, 'audio': {'codecs': [{'name': 'aac', 'value': 38}], 'containers': [{'name': 'ts', 'value': 38}]}, 'name': 'All'}
2025-04-29 10:11:08.976 DEBUG (MainThread) [custom_components.tdarr.sensor] {'totalFiles': 3609, 'totalTranscodeCount': 2603, 'sizeDiff': 354.6957962010056, 'totalHealthCheckCount': 8374, 'status': {'transcode': [{'name': 'Not required', 'value': 1068}, {'name': 'Queued', 'value': 26}, {'name': 'Transcode success', 'value': 2515}], 'healthcheck': [{'name': 'Queued', 'value': 1}, {'name': 'Success', 'value': 3608}]}, 'video': {'codecs': [{'name': 'h264', 'value': 26}, {'name': 'hevc', 'value': 3583}], 'containers': [{'name': 'mkv', 'value': 3583}, {'name': 'ts', 'value': 26}], 'resolutions': [{'name': '1080p', 'value': 1580}, {'name': '480p', 'value': 52}, {'name': '4KUHD', 'value': 1}, {'name': '576p', 'value': 1}, {'name': '720p', 'value': 1975}]}, 'audio': {'codecs': [], 'containers': []}, 'name': 'Platte 1 - D'}
2025-04-29 10:11:08.976 DEBUG (MainThread) [custom_components.tdarr.sensor] {'totalFiles': 32991, 'totalTranscodeCount': 25969, 'sizeDiff': 2.28257907461375, 'totalHealthCheckCount': 74296, 'status': {'transcode': [{'name': 'Not required', 'value': 5313}, {'name': 'Transcode success', 'value': 27678}], 'healthcheck': [{'name': 'Queued', 'value': 38}, {'name': 'Success', 'value': 32953}]}, 'video': {'codecs': [{'name': 'h264', 'value': 2}, {'name': 'hevc', 'value': 32927}, {'name': 'vp9', 'value': 24}], 'containers': [{'name': 'mkv', 'value': 32953}], 'resolutions': [{'name': '1080p', 'value': 1637}, {'name': '1440p', 'value': 2}, {'name': '480p', 'value': 10332}, {'name': '576p', 'value': 1682}, {'name': '720p', 'value': 19300}]}, 'audio': {'codecs': [{'name': 'aac', 'value': 38}], 'containers': [{'name': 'ts', 'value': 38}]}, 'name': 'Platte 2 - G'}
```

![Image](https://github.com/user-attachments/assets/94d084d6-90b4-41b3-bc83-eb73c53062a1)
As you can see, the sensor has gaps in its "Stats Speicher". This always happens when Tdarr isn't connected. I have a monitoring system that monitors Tdarr, and it's never failed.

[Transcode System](https://softarchivinfo.servebeer.com:3001/)

Following from this:
```
2025-04-29 10:11:32.238 DEBUG (MainThread) [custom_components.tdarr.switch] j2So47vxe
2025-04-29 10:11:32.238 DEBUG (MainThread) [custom_components.tdarr.switch] {'icon': 'mdi:pause-circle', 'name': 'pauseAll', 'data': 'globalsettings'}
2025-04-29 10:11:32.238 DEBUG (MainThread) [custom_components.tdarr.switch] pauseAll
2025-04-29 10:11:32.239 DEBUG (MainThread) [custom_components.tdarr.switch] {'icon': 'mdi:calendar-remove', 'name': 'ignoreSchedules', 'data': 'globalsettings'}
2025-04-29 10:11:32.239 DEBUG (MainThread) [custom_components.tdarr.switch] ignoreSchedules
2025-04-29 10:11:32.244 WARNING (MainThread) [homeassistant.components.automation.tdarr_error_messages] Tdarr Error Messages: Already running
2025-04-29 10:11:32.245 WARNING (MainThread) [homeassistant.components.automation.tdarr_error_messages] Tdarr Error Messages: Already running
2025-04-29 10:11:42.231 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform tdarr is taking over 10 seconds.
```

**Comment by itchannel** [comment]
Have you got quite a few of these errors in your logs" Tdarr Error Messages: Already running". As agreed it shouldn't be going unavailable but that log makes it look like it's trying to restart a lot. Also 24 seconds is ridiculously long to fetch data.  Is your tdarr on the same network as your HA instance? Just wondering if it's timing out due to latency.

**Comment by TheMRX13** [comment]
Tdarr is in the Same Network. I tryed to access the API dirctly.

# Edit 
*i found out where "Tdarr Error Messages: Already running" is comming from*
"Tdarr Error Messages: Already running" is an Automation what i have. im Sending Notification with that to my phone is there is a stage, healthcheck or transcode error.

![Image](https://github.com/user-attachments/assets/1d9ff837-2bbc-47db-b20b-dbcac58fd06d)

```powershell
$headers = @{
    "x-api-key" = "*********"
    "Content-Type" = "application/json"
}

$body = '{
  "data": {
    "collection": "StatisticsJSONDB",
    "mode": "getById",
    "docID": "statistics",
    "obj": {}
  }
}'

$url = "http://192.168.31.83:8265/api/v2/cruddb"

$start = Get-Date
try {
    $response = Invoke-RestMethod -Uri $url -Method Post -Headers $headers -Body $body

    $end = Get-Date
    $duration = $end - $start

    Write-Host "Responsetime: $($duration.TotalSeconds) Seconds"
    Write-Host "from Tdarr:"
    $response | ConvertTo-Json -Depth 10
}
catch {
    $end = Get-Date
    $duration = $end - $start
    Write-Host "Eror after $($duration.TotalSeconds) Seconds:"
    Write-Host $_
}
```

**Comment by itchannel** [comment]
I've found a big with the refresh interval when setting in options. That will be fixed in a new commit. I've set my refresh to 2 seconds but unable to get it to go unavailable at present.

**Comment by itchannel** [comment]
Give this version a go. I've fixed a couple of bugs and refactored the tdarr.py file https://github.com/itchannel/tdarr_ha/releases/tag/1.19-Beta

**Comment by TheMRX13** [comment]
Installed it and tested it. Dont get any connection now. 
```
2025-04-29 13:14:13.366 ERROR (SyncWorker_0) [custom_components.tdarr.tdarr] Request error for stats/get-pies: HTTPConnectionPool(host='192.168.31.83', port=8265): Read timed out. (read timeout=10)
```

Tryed to remove the Tdarr Server and added it again. it got added but everything is unavailable. and got this error on log.

```py
2025-04-29 13:16:53.508 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tdarr platform for sensor: 'name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/tdarr/sensor.py", line 28, in async_setup_entry
    sensors.append(TdarrSensor(entry, value, config_entry.options, "library"))
                   ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tdarr/sensor.py", line 64, in __init__
    self._device_id = "tdarr_library_" + self.sensor["name"]
                                         ~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
```

# Edit

After couple minutes every entity got removed. Only have the buttons now. 

![Image](https://github.com/user-attachments/assets/6bd77f7e-4a20-4a58-95e6-bca4da94cb3c)

**Comment by itchannel** [comment]
Try this version it fixes the sensor name issue. https://github.com/itchannel/tdarr_ha/releases/tag/1.19-Beta3

If you do still have time timeout error modify line 14 in tdarr.py and change the timeout value to something like 30 or 60 seconds. 

File: tdarr.py (Line 14)
```
def __init__(self, url: str, port: str, apikey: str = "", timeout: int = 10):
```

**Comment by TheMRX13** [comment]
i got all entitys back with timeout 60 but still needs 20 - 30 seconds for fetching data. Another stuff what i found: while the log is showing updating The UI is not updating. While Tdarr has 50 files in queue the integration still shows 53 but updated in log 3 times. 

Sorry for my bad english

**Comment by itchannel** [comment]
I can't replicate the 20-30seconds on my end, max it takes is 2 seconds to retrieve data for me. The UI not updating might be a result of me adding caching so will take a look later today.

**Comment by TheMRX13** [comment]
i Think i Found the issue. I Turned off my Wireguard Server because maintance. The integration is updating in 1 - 2 seconds. lets see what i happening when im finish and my wireguard is up again.

**Comment by TheMRX13** [comment]
When the WireGuard server is running, the Tdarr integration becomes very slow and takes up to 30 seconds to update. However, when the WireGuard server is stopped, the integration updates in just 1 to 3 seconds. I have already moved the WireGuard server to another machine to Fix it. 

However, I discovered another issue:
Although the Tdarr integration receives new data within 1 to 3 seconds (as shown in the log), the entities themselves do not update in the integration. Please refer to the attached GIF-you can see the integration, the log, and Tdarr itself for reference.

![Image](https://github.com/user-attachments/assets/54747988-e032-4309-8573-17afe1dfcc6a)

**Comment by TheMRX13** [comment]
This integration is not maintaned. im Switchting to https://github.com/deosrc/tdarr_ha Tdarr Integration by deosrc

**Comment by TheMRX13** [comment]
This is Done for me. I created my own fork. I added some things and fixed the Api key issue.
